server:
  port: 8080

spring:
  application:
    name: vox-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/vox
    username: vox_admin
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update # In production, this should be 'validate', but for dev 'update' is fine
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect